version: "3.9"
services:
  ice-breakun:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NUXT_HOST=0.0.0.0
      - NUXT_PORT=3000
